### ISSUE TITLE
Методы проверок должны возвращать ошибки явно

### ISSUE THREAD

**Issue by chiliec** [asuleymanov/golos-go#3]
Все методы из файла https://github.com/asuleymanov/golos-go/blob/master/client/verify.go возвращают `false` когда не удалось подключиться к блокчейну, что не всегда является ожидаемым значением. Они должны возвращать ошибку если она произошла.

**Comment by asuleymanov** [comment]
Ну так вроде false и значит что то что надо было найти не найдено.

**Comment by Chiliec** [comment]
false от ошибки подключения и false от блокчейна — совершенно разные значения )

**Comment by asuleymanov** [comment]
Можешь пример привести как ты это видишь?
А то что то я не сильно въехал.

**Comment by Chiliec** [comment]
Таска появилась из практического кейса. Делается [регулярная проверка делегированности постинг-ключа](https://github.com/GolosTools/golos-vote-bot/blob/2a6dbc98005e2c6e1ae49c7ce902abd755d1f88e/main.go#L748) и аккаунт исключается, если возвращается false. При невозможности соединения возвращается такой же false и исключаются так же активные аккаунты.
