### ISSUE TITLE
Unnecessary OptionsTrue & OptionsFalse

### ISSUE THREAD

**Issue by vovapi** [asuleymanov/golos-go#34]
https://github.com/asuleymanov/golos-go/blob/77ddcaa9595a45f9e0798e09ab36090b4a2c3dca/client_type.go#L7-L12

Why you need this? Why not just use true, false?

**Comment by vovapi** [comment]
Can you please link the code where it is used? 

I'm having trouble finding it.

**Comment by asuleymanov** [comment]
This is used only in one place.
In the file helper.go function GetCommentOptionsOperation.

**Comment by vovapi** [comment]
So it must be:
https://github.com/asuleymanov/golos-go/blob/07c4201323f897059071e759ae92c765d34b0d10/helper.go#L156-L162

So `OptionsTrue` is used

Why not just do: 
```go
av = true
```
?
(because it's the same thing)

**Comment by asuleymanov** [comment]
To be honest, I did this for a long time and do not remember the reason why. Maybe after that I changed the approach. And in this regard, your option will probably be able to work. I'll try and test how it will be when using your option.

**Comment by asuleymanov** [comment]
Yes, you were right.
I will remove these variables as unnecessary.
