### ISSUE TITLE
FollowerList doesn't work on > 1000 followers

### ISSUE THREAD

**Issue by vovapi** [asuleymanov/golos-go#37]
When getting follower list of account that has more than 1000 followers:
1. First 1000 followers is repeated again and again. Only first 1000 unique followers will be on that list.
1.  Follower number is rounded up to a thousands (e.g. 2345 is rounded up to a 3000)

Code to reproduce: [follower_list.go](https://gist.github.com/vovapi/174c20db1e161d9c33fd57602e5bc5d4)

The first part of these is caused by omitting `start` parameter on get_followers:
https://github.com/asuleymanov/golos-go/blob/ba3de56791608304d5d14c72e269b9bf6c7fa48e/helper.go#L28
The second part is caused by doing batch get wrong. The batch get logic needs rewrite

**Comment by vovapi** [comment]
This is true about following list as well

**Comment by asuleymanov** [comment]
Done
https://github.com/asuleymanov/golos-go/commit/81854219411fa36539b43a07d511601bd8fcd959
