### ISSUE TITLE
Calculated voting power differs from info one

### ISSUE THREAD

**Issue by vovapi** [asuleymanov/golos-go#38]
Subject

Reproduce: [voting_power.go](https://gist.github.com/vovapi/eba91aa5b27c98ee80a8c831d1bc1887)

**Comment by vovapi** [comment]
Is this helper is used at all? Considering that this info is available in account info?

**Comment by asuleymanov** [comment]
It is useful because the update in the account data is rare. And he calculates the data for a specific moment.
Personally, in my programs, I use it.

**Comment by vovapi** [comment]
Ok, I thought it was a bug. My mistake
