### ISSUE TITLE
Multiple unhandled errors

### ISSUE THREAD

**Issue by vovapi** [asuleymanov/golos-go#39]
User input data isn't validated, even through errors:

`functions.go`
* https://github.com/asuleymanov/golos-go/blob/9102368685c740a5de5e965a99d70fd9771f6b69/functions.go#L80
* https://github.com/asuleymanov/golos-go/blob/9102368685c740a5de5e965a99d70fd9771f6b69/functions.go#L330
* https://github.com/asuleymanov/golos-go/blob/9102368685c740a5de5e965a99d70fd9771f6b69/functions.go#L804

`helper.go`
* https://github.com/asuleymanov/golos-go/blob/9102368685c740a5de5e965a99d70fd9771f6b69/helper.go#L24
* https://github.com/asuleymanov/golos-go/blob/9102368685c740a5de5e965a99d70fd9771f6b69/helper.go#L45
* https://github.com/asuleymanov/golos-go/blob/9102368685c740a5de5e965a99d70fd9771f6b69/helper.go#L207
* https://github.com/asuleymanov/golos-go/blob/9102368685c740a5de5e965a99d70fd9771f6b69/helper.go#L216

`keys.go`
* https://github.com/asuleymanov/golos-go/blob/9102368685c740a5de5e965a99d70fd9771f6b69/keys.go#L74

`newfunc.go`
* https://github.com/asuleymanov/golos-go/blob/9102368685c740a5de5e965a99d70fd9771f6b69/newfunc.go#L39

`encoding/transaction/encoder.go`
* https://github.com/asuleymanov/golos-go/blob/9102368685c740a5de5e965a99d70fd9771f6b69/encoding/transaction/encoder.go#L135
* https://github.com/asuleymanov/golos-go/blob/9102368685c740a5de5e965a99d70fd9771f6b69/encoding/transaction/encoder.go#L176

`transactions`
* https://github.com/asuleymanov/golos-go/blob/9102368685c740a5de5e965a99d70fd9771f6b69/transactions/sign_the_shit.go#L19
* https://github.com/asuleymanov/golos-go/blob/9102368685c740a5de5e965a99d70fd9771f6b69/transactions/signed_transaction.go#L19

etc... 

This includes not the obvious ones like: 
https://github.com/asuleymanov/golos-go/blob/9102368685c740a5de5e965a99d70fd9771f6b69/verify.go#L17-L22
This makes debugging extremely frustrating

**Comment by asuleymanov** [comment]
Well, everything is clear. I will rule it. I just did not get my hands on it.
But I do not quite understand the latter. What do you mean?

**Comment by vovapi** [comment]
In the last example, when, for example, a network error is occurred, you won't get an error. You'll simply get a false result. So you won't be able to do something about it.
I think this should distinct between an "OK" response (true, false) and "ERROR" response.
This is debatable though...

**Comment by asuleymanov** [comment]
The second parameter in this paragraph is not an error.

https://github.com/asuleymanov/golos-go/blob/9102368685c740a5de5e965a99d70fd9771f6b69/keys.go#L74

**Comment by asuleymanov** [comment]
https://github.com/asuleymanov/golos-go/commit/bcdf15e6db3f0c7da0cb580926a8f448a79db6ab
