### ISSUE TITLE
Vote should return error on wrong weight

### ISSUE THREAD

**Issue by vovapi** [asuleymanov/golos-go#40]
Modification of user input is confusing
https://github.com/asuleymanov/golos-go/blob/9102368685c740a5de5e965a99d70fd9771f6b69/functions.go#L24-L27

**Comment by asuleymanov** [comment]
In the sense of confusion?

**Comment by asuleymanov** [comment]
Yes, here you are most likely right. Instead of correcting incorrect entry, it is better to give an error with explanations. This I will try to do in the near future. Then I'll have to dig in the library.

**Comment by vovapi** [comment]
So when a user sends invalid input, this input is modified and processed.
This can be confusing in a following way: this user is checking results and getting the result that he isn't anticipated: action has different data. This is confusing.
I think it needs to return an error for data that isn't valid.

**Comment by vovapi** [comment]
Thanks!

- - -
// TODO signature

**Comment by asuleymanov** [comment]
https://github.com/asuleymanov/golos-go/commit/bcdf15e6db3f0c7da0cb580926a8f448a79db6ab
