### ISSUE TITLE
Follows: user input validation

### ISSUE THREAD

**Issue by vovapi** [asuleymanov/golos-go#41]
Comment says you should pass blog, ignore or empty for a `what` value
But nothing prevents you from doing this:
https://github.com/asuleymanov/golos-go/blob/9102368685c740a5de5e965a99d70fd9771f6b69/functions.go#L164-L177

**Comment by asuleymanov** [comment]
You mean that you need to embed a test?

**Comment by vovapi** [comment]
I think it vould be reasonable to check input data (`what` parameter) and if it is invalid, then return an error

**Comment by asuleymanov** [comment]
I think here you are right. This is most likely to be combined with the question of https://github.com/asuleymanov/golos-go/issues/40
