### ISSUE TITLE
Login: implement login operation

### ISSUE THREAD

**Issue by vovapi** [asuleymanov/golos-go#42]
For some reason Login constructs operation in a weird way
https://github.com/asuleymanov/golos-go/blob/9102368685c740a5de5e965a99d70fd9771f6b69/functions.go#L301

**Comment by vovapi** [comment]
Why not use `json.Marshal` like everywhere else?

**Comment by asuleymanov** [comment]
I had such an idea. But for now I do not think this is a priority. But it remains in the plans.

**Comment by asuleymanov** [comment]
https://github.com/asuleymanov/golos-go/commit/bcdf15e6db3f0c7da0cb580926a8f448a79db6ab
